services:
  - type: web
    name: retina-unet
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn dashboard.app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: PORT
        generateValue: true
